# just a workaround :)
---
- name: SOME MAGIC...
  hosts: windows
  gather_facts: no
  tasks:
  - name: Disable Hibernation 1
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateFileSizePercent
      data: 0
      datatype: dword
      state: present
    register: deactive
      
  - name: Disable Hibernation 2
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateEnabled
      data: 0
      datatype: dword
      state: present

  - name: Disable First Logon Animations
    win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
      name: EnableFirstLogonAnimation
      data: 0
      datatype: dword
      state: present

  - name: Disable windows defender sending sample
    ansible.windows.win_powershell: 
      script: |
        Set-MpPreference -MAPSReporting 0; Set-MpPreference -SubmitSamplesConsent 2;

  - name: Allow RDP Connections
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      data: 0
      datatype: dword
      state: present

  - name: Firewall rule to allow RDP on TCP port 3389
    community.windows.win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Reboot before domain creation
    win_reboot:
    when: deactive.changed
